const nuncaNunca = [
{tipo: "Nunca Nunca",text:"Yo nunca he dicho claro que sí guapi (bebe)"},
{tipo: "Nunca Nunca",text:"Yo nunca he dicho a nadie “Bienvenido a tu cinta"},
{tipo: "Nunca Nunca",text:"Yo nunca he dejado caer mi móvil al WC"},
{tipo: "Nunca Nunca",text:"Yo nunca he vuelto con mi ex"},
{tipo: "Nunca Nunca",text:"Yo nunca me he liado con el ex de un amig@"},
{tipo: "Nunca Nunca",text:"Yo nunca me he tirado un pedo y he dicho “que mal huele” para despistar"},
{tipo: "Nunca Nunca",text:"Yo nunca he dicho que me encantaba un regalo y después lo he devuelto"},
{tipo: "Nunca Nunca",text:"Yo nunca he escuchado reggaetón en sesión privada en Spotify"},
{tipo: "Nunca Nunca",text:"Yo nunca he jugado a Stranger Things con las luces del árbol de Navidad"},
{tipo: "Nunca Nunca",text:"Yo nunca he tenido una época vegana/vegetariana y se lo he dicho a todo el mundo"},
{tipo: "Nunca Nunca",text:"Yo nunca he visto una serie solo por ver en bucle el culo del actor"},
{tipo: "Nunca Nunca",text:"Yo nunca he fingido amar un grupo de música cuando solo me se el nombre"},
{tipo: "Nunca Nunca",text:"Yo nunca he escrito a mi ex una noche de fiesta"},
{tipo: "Nunca Nunca",text:"Yo nunca he fingido estar en un videoclip cuando salgo de la ducha mientras pongo caras intensas en el espejo"},
{tipo: "Nunca Nunca",text:"Yo nunca he hecho un spoiler de Juego de Tronos"},
{tipo: "Nunca Nunca",text:"Yo nunca dudé de quién era el cuarto en el videoclip de Maluma"},
{tipo: "Nunca Nunca",text:"Yo nunca he hecho pis en una piscina con miedo por si aparecía el circulo rojo"},
{tipo: "Nunca Nunca",text:"Yo nunca he fingido que me llamaban para escapar de una cita"},
{tipo: "Nunca Nunca",text:"Yo nunca he estado más de tres días sin ducharme"},
{tipo: "Nunca Nunca",text:"Yo nunca me he apuntado al gimnasio pero no he ido jamás"},
{tipo: "Nunca Nunca",text:"Yo nunca he votado para que Cepeda se quede en OT"},
{tipo: "Nunca Nunca",text:"Yo nunca he stalkeado el instagram del el/la ex de mi novi@"},
{tipo: "Nunca Nunca",text:"Yo nunca me he dado el pisto en una entrevista de trabajo"},
{tipo: "Nunca Nunca",text:"Yo nunca he dicho Carpe Diem para convencer un amigo y salir de fiesta"},
{tipo: "Nunca Nunca",text:"Yo nunca he cantado en el Singstar “Cuando zarpa el amor” de Camela"},
{tipo: "Nunca Nunca",text:"Yo nunca he apuntado con la linterna mi boca para enseñarle las placas a un amigo"},
{tipo: "Nunca Nunca",text:"Yo nunca he abierto a la policía por haber hecho un fiestón en casa"},
{tipo: "Nunca Nunca",text:"Yo nunca me he imaginado siendo del sexo opuesto"},
{tipo: "Nunca Nunca",text:"Yo nunca he llamado mamá a mi profesora"},
{tipo: "Nunca Nunca",text:"Yo nunca me he reído con el humor de La Vida Moderno"},
{tipo: "Nunca Nunca",text:"Yo nunca me he pasado mi parada del tren volviendo de fiesta y he acabao en otra ciudad"},
{tipo: "Nunca Nunca",text:"Yo nunca he  perdido un iPhone"},
{tipo: "Nunca Nunca",text:"Yo nunca he llevado unas gafas de cristal solo por posturear"},
{tipo: "Nunca Nunca",text:"Yo nunca me autoavergüenzo de haber sido fan de Crepúsculo"},
{tipo: "Nunca Nunca",text:"Yo nunca he pesado la fruta, le he pegado el ticket y luego he metido más"},
{tipo: "Nunca Nunca",text:"Yo nunca mentí en el Yo Nunca"},
{tipo: "Nunca Nunca",text:"Yo nunca he estornudado y me ha salido un moco"},
{tipo: "Nunca Nunca",text:"Yo nunca he preguntado a alguien que no trabajaba en una tienda si tenía mi talla"},
{tipo: "Nunca Nunca",text:"Yo nunca he indicado mal un camino cuando me han preguntado"},
{tipo: "Nunca Nunca",text:"Yo nunca he olido mi propio pedo"},
{tipo: "Nunca Nunca",text:"Yo nunca he movido la boca aunque no me sepa la canción"},
{tipo: "Nunca Nunca",text:"Yo nunca he fingido un desmayo para darle dramatismo a una situación"},
{tipo: "Nunca Nunca",text:"Yo nunca he intentado mover cosas con la mente (sin resultado)"},
{tipo: "Nunca Nunca",text:"Yo nunca he flirteado con el novio de un amig@"},
{tipo: "Nunca Nunca",text:"Yo nunca he cotilleado a quién daba like mis exparejas"},
{tipo: "Nunca Nunca",text:"Yo nunca he mirado el papel después de ir al baño"},
{tipo: "Nunca Nunca",text:"Yo nunca he acosado por redes sociales a mi artista favorito"},
{tipo: "Nunca Nunca",text:"Yo nunca me he creído Mr Robot al instalar un programa pirata"},
{tipo: "Nunca Nunca",text:"Yo nunca he mandado un audio subidito de tono a mi madre por error"},
{tipo: "Nunca Nunca",text:"Yo nunca he matado a nadie"},
{tipo: "Cultura Chupistica", text:"Nombres de pokemones de la primera generación como, por ejemplo, Charmander."},
{tipo: "Cultura Chupistica", text:"Películas que repiten todo el año en la televisión abierta como, por ejemplo, Titanic."},
{tipo: "Cultura Chupistica", text:"Recorridos de las micros amarillas como, por ejemplo, 355 (La Florida-Lo Prado)"},
{tipo: "Cultura Chupistica", text:"Apodos cariñosos de Pinochet como, por ejemplo, “Mi General”"},
{tipo: "Cultura Chupistica", text:"Piñericosas del último tiempo como, por ejemplo, “Reino de Chile”"},
{tipo: "Cultura Chupistica", text:"Clásicos de la música euro como, por ejemplo, Coco Jambo"},
{tipo: "Cultura Chupistica", text:"Tragos de emergencia como, por ejemplo, Pichi de cangura"},
{tipo: "Cultura Chupistica", text:"Fetiches sexuales como, por ejemplo, lamer pies"},
{tipo: "Cultura Chupistica", text:"Neo-siutiquerías como, por ejemplo, decir ‘what the fuck’ en una conversación"},
{tipo: "Cultura Chupistica", text:"Títulos de películas porno como, por ejemplo, “Enfermeras ninfómanas”"},
{tipo: "Cultura Chupistica", text:"Errores garrafales en la primera cita como, por ejemplo, decir “te amo”"},
{tipo: "Cultura Chupistica", text:"Películas que tengan una secuela como, por ejemplo, “Volver al futuro”"},
{tipo: "Cultura Chupistica", text:"Bandas de música indie como, por ejemplo, eeeh… ummm. Bueh, revisen ustedes."},
{tipo: "Cultura Chupistica", text:"Errores urbanísticos/arquitectónicos como, por ejemplo, Malla Plaza Barón (Valpo), teleférico que conecta Sanhattan con Ciudad Empresarial pos hombre (Stgo)"},
{tipo: "Cultura Chupistica", text:"Cantantes románticos cursis como, por ejemplo, Douglas."},
{tipo: "Cultura Chupistica", text:"Bandas chilenas noventeras como, por ejemplo, Glup!"},
{tipo: "Cultura Chupistica", text:"Personajes recordados de las teleseries como, por ejemplo, Juan del burro (Pablo Schwarz) y Luis Miguel (su burro, en Sucupira)"},
{tipo: "Cultura Chupistica", text:"Álbumes clásicos de Salo como, por ejemplo, Dragon Ball Z."},
{tipo: "Cultura Chupistica", text:"Nombres de calles repetidas por todo Chile como, por ejemplo, Arturo Prat."},
{tipo: "Cultura Chupistica", text:"Empresas pulperas que patrocinan la Teletón como, por ejemplo, Banco de Chile/CCU."},
{tipo: "Cultura Chupistica", text:"Problemas que nunca solucionó Piñera como, por ejemplo, la educación."},
{tipo: "Cultura Chupistica", text:"Colores de la bandera de Chile como, por ejemplo, blanco (tema teledirigido: se cagarás al tercero después de ti)"},
{tipo: "Cultura Chupistica", text:"Personajes fachos de la televisión como, por ejemplo, la Maldonado (súper fácil, en realidad)"},
{tipo: "Cultura Chupistica", text:"Memes de la Internet como, por ejemplo, Forever alone"},
{tipo: "Cultura Chupistica", text:"Gentilicios de ciudades chilenas como, por ejemplo, porteño"},
{tipo: "Cultura Chupistica", text: "Partes del cuerpo que hay solo 1."},
{tipo: "Cultura Chupistica", text: "Partes del cuerpo que crecen."},
{tipo: "Cultura Chupistica", text: "Nombres de personas en árabe, en alemán, japonés, etc."},
{tipo: "Cultura Chupistica", text: "Nombre de los dientes."},
{tipo: "Cultura Chupistica", text: "Colores naturales de los ojos."},
{tipo: "Cultura Chupistica", text: "Nombre de los dedos de las manos."},
{tipo: "Cultura Chupistica", text: "Nombres de los personajes de los simpson."},
{tipo: "Cultura Chupistica", text: "Nombres k terminen con “s“."},
{tipo: "Cultura Chupistica", text: "Garabatos chilenos."},
{tipo: "Cultura Chupistica", text: "Nombres de los personajes del chavo del 8."},
{tipo: "Cultura Chupistica", text: "Nombres de marcas de auto."},
{tipo: "Cultura Chupistica", text: "Nombre de jugadores de fútbol chilenos que juegan o jugaron en el extranjero."},
{tipo: "Cultura Chupistica", text: "Nombres de los huesos del cuerpo humano."},
{tipo: "Cultura Chupistica", text: "Nombre de ciudades que tengan playas."},
{tipo: "Cultura Chupistica", text: "Nombres de mujeres k no terminen en a."},
{tipo: "Cultura Chupistica", text: "Cantantes de rock famosos."},
{tipo: "Cultura Chupistica", text: "Razas de perros."},
{tipo: "Cultura Chupistica", text: "Señaleticas de transito."},
{tipo: "Cultura Chupistica", text: "Nombre de las ciudades del mundo que empiecen con O."},
{tipo: "Cultura Chupistica", text: "Nombres de tragos."},
{tipo: "Cultura Chupistica", text: "Nombre de deportes q se jueguen con una pelota."},
{tipo: "Cultura Chupistica", text: "Nombre de comidas fritas."},
{tipo: "Cultura Chupistica", text: "nombres q empiecen con a."},
{tipo: "Cultura Chupistica", text: "Palabras que no tengan la A como por ejemploLibro, Pulmon etc."},
{tipo: "Cultura Chupistica", text: "Nombres de animales acuáticos."},
{tipo: "Cultura Chupistica", text: "Animales prehistóricos."},
{tipo: "Cultura Chupistica", text: "Nombres de comidas que lleven papas ejemplo pastel de papas."},
{tipo: "Cultura Chupistica", text: "Animales propios de Chile."},
{tipo: "Cultura Chupistica", text: "Palabras agudas terminadas en N tales como CAMIÓN."},
{tipo: "Cultura Chupistica", text: "Nombre antiguos como por ejemplo: gumercinda."},
{tipo: "Cultura Chupistica", text: "Películas Chilenas por ejemplo: Machuca."},
{tipo: "Cultura Chupistica", text: "Cosas que no pueden faltar en la cama como por ejemplo: colchón."},
{tipo: "Cultura Chupistica", text: "Nombres con los que se le puede llamar a un homosexual como por ejemplo fleto."},
{tipo: "Cultura Chupistica", text: "Nombres de equipos de futbol ej.: universidad católica."},
{tipo: "Cultura Chupistica", text: "Nombres de hombre q tengan “s” ej.: Andrés."},
{tipo: "Cultura Chupistica", text: "Nombres de frutas."},
{tipo: "Cultura Chupistica", text: "Planetas del sistema solar."},
{tipo: "Cultura Chupistica", text: "Marcas de cervezas."},
{tipo: "Cultura Chupistica", text: "Nombre solo instrumentos de cuerda como por ejemplo violín."},
{tipo: "Cultura Chupistica", text: "Nombre marcas de automóviles como por ejemplo Suzuki."},
{tipo: "Cultura Chupistica", text: "Marcas de celulares."},
{tipo: "Cultura Chupistica", text: "Los nombre de los presidentes de toda la historia de Chile."},
{tipo: "Cultura Chupistica", text: "Partes del cuerpo que tengan pelos."},
{tipo: "Cultura Chupistica", text: "Nombre los dibujos animados ochenteros como por ej.: he-man."},
{tipo: "Cultura Chupistica", text: "nombre marcas de cigarrillos."},
{tipo: "Cultura Chupistica", text: "Nombre signos zodiacales."},
{tipo: "Cultura Chupistica", text: "Nombres bíblicos como por ej.: Noé"},
]
export default nuncaNunca; 